cache = true
max_cache_age = "1d"
max_retries = 3
retry_wait_time = 2
timeout = 20
accept = [200, 204, 206, 429]
exclude = [
  '^http://localhost',
  '^http://127\\.0\\.0\\.1',
  'https://github.com/JordanLacroix/GenEngine/actions/workflows/scorecard.yml/badge.svg',
  'https://github.com/JordanLacroix/GenEngine/security/advisories/new'
]
