#!/usr/bin/env bash
# End-to-end proof that the AI assistant provider is genuinely wired: it enables an
# Azure AI Foundry aiProviders[] entry on a running instance, then asks for contextual
# help and asserts the answer came from the provider (source == "Ai"), not the offline
# rules.
#
# Disabled by default. It runs only when GENENGINE_AI_AZURE_FOUNDRY_KEY is set in this
# shell, because it makes a real, billable call to the configured deployment. Without the
# key it exits 0 after explaining why, so CI and a plain checkout never depend on a cloud
# credential — the same invariant the wiring itself honours.
#
# The key is only used as a presence gate here; the PlayerExperience process resolves it
# itself, from its own environment, through the env: secret scheme. This script never sees
# or forwards the secret value.
#
# See specs/platform-configuration.md § "Câblage du fournisseur d'assistant, de bout en bout".
set -euo pipefail

IDENTITY_URL="${IDENTITY_URL:-http://localhost:5203}"
CONFIGURATION_URL="${CONFIGURATION_URL:-http://localhost:5204}"
PLAYER_EXPERIENCE_URL="${PLAYER_EXPERIENCE_URL:-http://localhost:5205}"
FRONT_ID="${FRONT_ID:-default}"
ADMIN_USER_NAME="${GENENGINE_ADMIN_USER_NAME:-diapason-admin}"
ADMIN_PASSWORD="${GENENGINE_ADMIN_PASSWORD:-LocalDiapasonPassword!2026}"
ENDPOINT="${GENENGINE_AI_AZURE_FOUNDRY_ENDPOINT:-https://newfoundrymistral-resource.openai.azure.com/openai/v1}"
DEPLOYMENT="${GENENGINE_AI_AZURE_FOUNDRY_DEPLOYMENT:-gpt-4o}"
SECRET_REFERENCE="${GENENGINE_AI_AZURE_FOUNDRY_SECRET_REFERENCE:-env:GENENGINE_AI_AZURE_FOUNDRY_KEY}"

if [[ -z "${GENENGINE_AI_AZURE_FOUNDRY_KEY:-}" ]]; then
  echo "GENENGINE_AI_AZURE_FOUNDRY_KEY is not set: skipping the real provider call."
  echo "Set it (and the same variable on the PlayerExperience process) to run this proof."
  exit 0
fi

for command in curl jq; do
  command -v "$command" >/dev/null || { echo "Missing required command: $command" >&2; exit 1; }
done

login() {
  curl --fail --silent --show-error -H 'Content-Type: application/json' \
    -d "$(jq -n --arg u "$1" --arg p "$2" '{userName:$u,password:$p}')" \
    "$IDENTITY_URL/auth/login" | jq -er '.token'
}

echo "1/4 Enabling the Azure AI Foundry provider on front '$FRONT_ID'."
admin_token=$(login "$ADMIN_USER_NAME" "$ADMIN_PASSWORD")
document=$(curl --fail --silent --show-error -H "Authorization: Bearer $admin_token" \
  "$CONFIGURATION_URL/admin/configuration/$FRONT_ID")
revision=$(jq -er '.revision' <<<"$document")
updated_document=$(jq --arg e "$ENDPOINT" --arg d "$DEPLOYMENT" --arg s "$SECRET_REFERENCE" '
  .document
  | .aiProviders |= map(
      if .type == "AzureAiFoundry"
      then .enabled = true | .endpoint = $e | .deployment = $d | .authentication = "ApiKey" | .secretReference = $s
      else . end)' <<<"$document")

new_revision=$(jq -n --argjson d "$updated_document" --argjson r "$revision" '{expectedRevision:$r,document:$d}' \
  | curl --fail --silent --show-error -X PUT -H "Authorization: Bearer $admin_token" \
      -H 'Content-Type: application/json' -d @- \
      "$CONFIGURATION_URL/admin/configuration/$FRONT_ID" | jq -er '.revision')

echo "2/4 Publishing revision $new_revision."
curl --fail --silent --show-error -X POST -H "Authorization: Bearer $admin_token" \
  -H 'Content-Type: application/json' \
  -d "$(jq -n --argjson r "$new_revision" '{expectedRevision:$r}')" \
  "$CONFIGURATION_URL/admin/configuration/$FRONT_ID/publish" >/dev/null

echo "3/4 Registering a throwaway player."
player_user="ai-proof-$(date +%s)"
player_password="LocalAiProof!2026"
credentials=$(jq -n --arg u "$player_user" --arg p "$player_password" '{userName:$u,password:$p}')
curl --fail --silent --show-error -X POST -H 'Content-Type: application/json' \
  -d "$credentials" "$IDENTITY_URL/auth/register" >/dev/null
player_token=$(login "$player_user" "$player_password")

echo "4/4 Asking for contextual help and asserting source == \"Ai\"."
response=$(curl --fail --silent --show-error -X POST -H "Authorization: Bearer $player_token" \
  -H 'Content-Type: application/json' -d '{"context":"scenario"}' \
  "$PLAYER_EXPERIENCE_URL/me/experience/assistant/contextual-help")

source=$(jq -er '.source' <<<"$response")
echo "source=$source isFallback=$(jq -r '.isFallback' <<<"$response")"
jq -r '"message=\(.message)"' <<<"$response"

if [[ "$source" != "Ai" ]]; then
  echo "FAILED: expected source \"Ai\" from the provider, got \"$source\"." >&2
  echo "The offline fallback is intact, but the provider was not reached — check the key," >&2
  echo "the endpoint, the deployment name, and that the provider entry is enabled." >&2
  exit 1
fi

echo "OK: contextual help was generated by the Azure AI Foundry provider."
