// <auto-generated />
using System;
using GenEngine.PlayerExperience.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GenEngine.PlayerExperience.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlayerExperienceDbContext))]
    [Migration("20260720174735_AddPlayerStatValues")]
    partial class AddPlayerStatValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.OnboardingState", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TutorialId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedStepIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessedCommandIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SkippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ProfileId", "TutorialId", "Version");

                    b.ToTable("onboarding_states", (string)null);
                });

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.OwnedItem", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProfileId", "OfferId");

                    b.ToTable("owned_items", (string)null);
                });

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.PlayerJournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("JourneyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("ScenarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScenarioVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ProfileId", "OccurredAt");

                    b.HasIndex("ProfileId", "CategoryId", "OccurredAt");

                    b.HasIndex("ProfileId", "JourneyId", "OccurredAt");

                    b.HasIndex("ProfileId", "ScenarioId", "OccurredAt");

                    b.HasIndex("ProfileId", "Type", "OccurredAt");

                    b.ToTable("player_journal_entries", (string)null);
                });

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DefaultJourneyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FamiliarAccent")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FamiliarAxisSelectionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FamiliarCustomName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FamiliarForm")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("FamiliarHelpLevel")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FamiliarId")
                        .HasColumnType("uuid");

                    b.Property<int>("FamiliarInterventionFrequency")
                        .HasColumnType("integer");

                    b.Property<bool>("FamiliarProactive")
                        .HasColumnType("boolean");

                    b.Property<string>("FamiliarTone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FamiliarWritingStyle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("FinaleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinaleReachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FrontId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FrontId")
                        .IsUnique();

                    b.ToTable("player_profiles", (string)null);
                });

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.PlayerStatValue", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ProcessedCommandIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ProfileId", "Key");

                    b.ToTable("player_stat_values", (string)null);
                });

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.ScenarioMastery", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScenarioVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChoiceIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EndingIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("NodeIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProcessedCommandIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TotalObjectives")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProfileId", "ScenarioVersionId");

                    b.HasIndex("ProfileId", "ScenarioId");

                    b.ToTable("scenario_masteries", (string)null);
                });

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.WalletEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("wallet_entries", (string)null);
                });

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.OnboardingState", b =>
                {
                    b.HasOne("GenEngine.PlayerExperience.Domain.PlayerProfile", null)
                        .WithMany("OnboardingStates")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.OwnedItem", b =>
                {
                    b.HasOne("GenEngine.PlayerExperience.Domain.PlayerProfile", null)
                        .WithMany("OwnedItems")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.PlayerJournalEntry", b =>
                {
                    b.HasOne("GenEngine.PlayerExperience.Domain.PlayerProfile", null)
                        .WithMany("JournalEntries")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.PlayerStatValue", b =>
                {
                    b.HasOne("GenEngine.PlayerExperience.Domain.PlayerProfile", null)
                        .WithMany("StatValues")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.ScenarioMastery", b =>
                {
                    b.HasOne("GenEngine.PlayerExperience.Domain.PlayerProfile", null)
                        .WithMany("ScenarioMasteries")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.WalletEntry", b =>
                {
                    b.HasOne("GenEngine.PlayerExperience.Domain.PlayerProfile", null)
                        .WithMany("WalletEntries")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenEngine.PlayerExperience.Domain.PlayerProfile", b =>
                {
                    b.Navigation("JournalEntries");

                    b.Navigation("OnboardingStates");

                    b.Navigation("OwnedItems");

                    b.Navigation("ScenarioMasteries");

                    b.Navigation("StatValues");

                    b.Navigation("WalletEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
