namespace GenEngine.PlayerExperience.Application;

/// <summary>
/// The kind of help actually served. Modalities are explicit because they are not
/// interchangeable: a discreet hint and the explanation of a blocking condition
/// disclose very different amounts of the scenario, so the assistant policy and
/// the player's help level decide which one is allowed.
/// </summary>
public enum HelpModality
{
    /// <summary>No help was served, because the familiar was asked to stay quiet.</summary>
    None,

    /// <summary>A discreet nudge that does not name the answer.</summary>
    Hint,

    /// <summary>The current objective restated.</summary>
    Objective,

    /// <summary>Consequences the player already knows about.</summary>
    Consequence,

    /// <summary>Why a visible option is unavailable.</summary>
    Blocker,

    /// <summary>A warning that this path has already been explored.</summary>
    KnownPathWarning,
}

/// <summary>Where the served message actually came from.</summary>
public static class HelpSources
{
    /// <summary>Built-in generic text; nothing scenario-specific was available.</summary>
    public const string OfflineRule = "OfflineRule";

    /// <summary>Author help carried by the published scenario version.</summary>
    public const string ScenarioHelp = "ScenarioHelp";

    /// <summary>Client-supplied override, kept for backwards compatibility.</summary>
    public const string AuthorHint = "AuthorHint";

    /// <summary>Generated by a configured AI provider.</summary>
    public const string Ai = "Ai";

    /// <summary>The already-explored warning required by the assistant policy.</summary>
    public const string KnownPathWarning = "KnownPathWarning";

    /// <summary>The familiar deliberately stayed silent.</summary>
    public const string Suppressed = "Suppressed";
}

/// <summary>
/// Author help extracted from a published scenario version. This is an
/// anti-corruption projection: PlayerExperience never references the narrative
/// engine, it only reads the few presentation fields it needs out of the
/// published snapshot JSON.
/// </summary>
public sealed record AuthorHelpView(string? Hint, string? Objective, string? Consequence, string? Blocker)
{
    public bool IsEmpty => Hint is null && Objective is null && Consequence is null && Blocker is null;
}

/// <summary>Everything PlayerExperience needs from a published scenario version to help a player.</summary>
public sealed record ScenarioHelpSnapshot(
    string Title,
    string? NodeId,
    string? NodeText,
    IReadOnlyList<string> VisibleChoiceTexts,
    AuthorHelpView? NodeHelp,
    AuthorHelpView? ChoiceHelp);

/// <summary>
/// Port to Authoring's internal published-version route. The implementation lives
/// in Infrastructure and is expected to degrade to <c>null</c> — never to throw —
/// when Authoring is unavailable, so contextual help can always fall back offline.
/// </summary>
public interface IScenarioHelpProvider
{
    Task<ScenarioHelpSnapshot?> GetAsync(Guid scenarioVersionId, string? nodeId, string? choiceId, CancellationToken cancellationToken);
}

/// <summary>
/// Exactly what is sent to an AI provider. This record is the whole payload: there
/// is no hidden field, and nothing here identifies the player. It deliberately
/// carries no user id, no display name, no wallet, no journal and no progression
/// history — only the public scenario content the player is already looking at,
/// plus the familiar's presentation settings.
/// </summary>
public sealed record AssistantAiContext(
    string FrontId,
    string Context,
    HelpModality Modality,
    int HelpLevel,
    string ScenarioTitle,
    string? NodeId,
    string? NodeText,
    IReadOnlyList<string> VisibleChoiceTexts,
    string? AuthorHelpText,
    bool AlreadyExplored,
    string FamiliarName,
    string FamiliarTone,
    string FamiliarWritingStyle);

/// <summary>
/// A configured AI provider as PlayerExperience needs to reach it. The
/// <see cref="SecretReference"/> is the opaque reference (for example
/// <c>env:GENENGINE_AI_AZURE_FOUNDRY_KEY</c>), never a resolved secret: the
/// infrastructure resolves it locally. <see cref="Type"/> mirrors Configuration's
/// provider-type names so the client can pick the Azure AI Foundry entry.
/// </summary>
public sealed record AssistantAiProvider(
    string Name,
    string Type,
    bool Enabled,
    string Endpoint,
    string Deployment,
    string? SecretReference);

/// <summary>
/// Port to Configuration's internal AI-provider route. The implementation lives in
/// Infrastructure and is expected to degrade to an empty list — never to throw — when
/// Configuration is unavailable, so the assistant can always fall back offline.
/// </summary>
public interface IAssistantProviderCatalog
{
    Task<IReadOnlyList<AssistantAiProvider>> GetAsync(string frontId, CancellationToken cancellationToken);
}

/// <summary>
/// Port to an AI provider. The implementation lives in Infrastructure and resolves
/// its own credentials locally; no secret ever reaches this layer, and the
/// published configuration document PlayerExperience reads has its
/// <c>secretReference</c> redacted by Configuration before it is served.
/// <para>
/// An implementation must return <c>null</c> rather than throw when it is
/// disabled, unreachable, times out or produces an unusable answer: contextual
/// help then degrades to the offline rules.
/// </para>
/// </summary>
public interface IAssistantAiClient
{
    /// <summary>Whether a provider is actually configured in this deployment.</summary>
    bool IsConfigured { get; }

    Task<string?> GenerateAsync(AssistantAiContext context, CancellationToken cancellationToken);
}

/// <summary>
/// Selects which modality the assistant is allowed to serve, from the player's
/// help level. The ladder is deliberate: a low level restates the goal without
/// disclosing anything, and only a high level explains what blocks an option.
/// </summary>
public static class HelpModalityPolicy
{
    public static HelpModality ForHelpLevel(int helpLevel) => Math.Clamp(helpLevel, 0, 5) switch
    {
        0 => HelpModality.Objective,
        1 or 2 => HelpModality.Hint,
        3 => HelpModality.Consequence,
        _ => HelpModality.Blocker,
    };

    /// <summary>
    /// Text for the preferred modality, degrading down the ladder when the author
    /// wrote nothing for it. The order is fixed so the same request always yields
    /// the same modality for the same content.
    /// </summary>
    public static (HelpModality Modality, string Text)? Resolve(AuthorHelpView? help, HelpModality preferred)
    {
        if (help is null || help.IsEmpty)
        {
            return null;
        }

        foreach (HelpModality candidate in Ladder(preferred))
        {
            string? text = candidate switch
            {
                HelpModality.Hint => help.Hint,
                HelpModality.Objective => help.Objective,
                HelpModality.Consequence => help.Consequence,
                HelpModality.Blocker => help.Blocker,
                _ => null,
            };

            if (!string.IsNullOrWhiteSpace(text))
            {
                return (candidate, text);
            }
        }

        return null;
    }

    private static IEnumerable<HelpModality> Ladder(HelpModality preferred)
    {
        yield return preferred;
        foreach (HelpModality fallback in new[]
        {
            HelpModality.Hint,
            HelpModality.Objective,
            HelpModality.Consequence,
            HelpModality.Blocker,
        })
        {
            if (fallback != preferred)
            {
                yield return fallback;
            }
        }
    }
}